server:
  waitTimeInMsWhenSyncEmpty: 0
  port: 8761

spring:
  application:
    name: eureka
  # 安全认证的配置
security:
  basic:
    enabled: true
  user:
    name: zzh
    password: zzh

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: false
  instance:
    hostname: eureka

logging:
  file: /tmp/eureka.log