server:
  port: 82
  context-path: /master
mybatis:
  mapperLocations: classpath*:mapper/*.xml
spring:
  datasource:
    platform: h2
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
    driver-class-name: org.h2.Driver