server:
  port: 84
  context-path: /config
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/regedit0726/spring-cloud-practice.git
          search-paths: config-repo
          default-label: zzh