server:
  port: 81
  context-path: /web

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

#eureka:
#  username: zzh
#  password: zzh
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://${eureka.username}:${eureka.password}@eureka.zzh.com:8761/eureka/
#    healthcheck:
#      enabled: true
#  instance:
#    appname: spring-cloud-web
#    leaseRenewalIntervalInSeconds: 10
##    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
#    hostname: localhost

logging:
  file: /logs/web.log

xx:
  test:
    hehe: normal
    txtarray: 1,2,3,a  #这种对象形式的，只能单独写一个对象去接收，所以无法使用@value注解获取
    listmap:
      - host: zxj
        port: 10
        active: 9
      - host: ly
        port: 11
        active: 8
    liststr:
      - name
      - value
    map:
      a: a
      b: b

myProps: #自定义的属性和值
  simpleProp: simplePropValue
  arrayProps: 1,2,3,4,5
  listProp1:   #List中的元素是Map
    - name: abc
      value: abcValue
    - name: efg
      value: efgValue
  listProp2:
    - config2Value1
    - config2Vavlue2
  mapProps:
    key1: value1
    key2: value2